CREATE TABLE DEPARTMENT(
	DEPTNO NUMBER NOT NULL,
	DEPTNAME VARCHAR2(50) NOT NULL,
	FLLOR NUMBER NULL,
	PRIMARY KEY (DEPTNO)
);


CREATE TABLE EMPLOYEE(
	EMPNO NUMBER NOT NULL PRIMARY KEY,
	EMPNAME VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(50) NULL,
	MANAGER NUMBER NULL,
	SALARY NUMBER NULL,
	DNO NUMBER NULL,
	FOREIGN KEY(MANAGER) REFERENCES EMPLOYEE(EMPNO),
	FOREIGN KEY(DNO) REFERENCES DEPARTMENT(DEPTNO)
);